---
abstract: 'My Sample Module version 2'
author:
  - 'Yoko Oyama <yowcow@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4218, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MySample-Module2
provides:
  MySample::Module2:
    file: lib/MySample/Module2.pm
    version: v0.0.1
requires:
  File::Spec: '0'
  Moo: '0'
  namespace::clean: '0'
  strictures: '2'
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
